### ISSUE TITLE
"searchAsYouTypeEnabled" has no power

### ISSUE THREAD

**Issue by anmiles** [dixahq/kb-typescript-starter#18]
Hi there,

I clone the repository, then add `"searchAsYouTypeEnabled": true` to `settings.json` and then run `npm install && npm start`.
Website is working on `localhost:4000` but search box doesn't show dropdown with suggestions whatever I enter in.
Is there something other I have to do to get suggestions dropdown working?
![image](https://user-images.githubusercontent.com/2843316/163362605-989bb937-39bf-4c99-a783-03dd26577e56.png)

**Comment by kristian-puccio** [comment]
Heya @anmiles... So a couple of things.
First to get search as you type working you also need to set an option in the Config file:
```ts
  import { Config, SearchStyle } from '@elevio/kb-kit/lib/Config';

const config: Config = {
   ...
  searchStyle: SearchStyle.dropdown,
}
```
That tells the KB to not show a search page but instead use a dropdown.

Unfortunately the starter kit doesn't include the functionality to get that to work but I'll push a commit to get it to do so.
I'll ping you when it's live.

**Comment by kristian-puccio** [comment]
Heya @anmiles the code to try out search dropdown and live search have now been added via #19 .

Hope this helps.
Shout out if you have any questions.
