### ISSUE TITLE
Cannot install @elevio/kb-kit@^0.1.30

### ISSUE THREAD

**Issue by anmiles** [dixahq/kb-typescript-starter#20]
Specified in `package.json`:
```
"@elevio/kb-kit": "^0.1.30"
```
Running `npm install` failed with an error:
`No matching version found for @elevio/kb-kit@^0.1.30`

NPM page says that recent version is 0.1.29: https://www.npmjs.com/package/@elevio/kb-kit
And github link is not working on that page: https://github.com/dixahq/elevio-kb-kit

**Comment by kristian-puccio** [comment]
Apologies @anmiles that should be fixed now
